int16 auto_control # 0
int16 control_mode # 1
int16 acc_cmode # 2
int16 acc_pos_ref # 3
float32 acc_vel_ref # 4
int16 acc_frc_ref # 5
int16 brk_cmode # 6
int16 brk_pos_ref # 7
float32 brk_vel_ref # some thing wrong-> error ros2 topic echo
int16 brk_frc_ref
int16 tir_cmode
float32 tir_ang_ref
float32 tir_vel_ref
int16 tir_frc_ref
int16 winker_l
int16 winker_r
int16 gear_d
int16 gear_r
uint16 emergency_stop
int16 wd_count
float32 pc_speed_mps
float32 pc_yawrate
float32 pc_speedr_mps
float32 pc_speedl_mps